---
title: 2020 C3 San Diego
timezone: America/New_York
collections:
  agenda:
    title: Agenda
    output: true
    permalink: "/agenda/:title/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
  values:
    has-introduction: true
    introduction-background-color: bg-white
    introduction-header: Introduction
    introduction-body: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
      do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
      veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum
      dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.
    introduction-has-button: true
    introduction-button-label: Optional Button
    introduction-button-url: "#"
    introduction-button-style: primary
- scope:
    path: ''
    type: agenda
  values:
    description: Provide description of event
    event:
      date: Select event date
      start-time: Select event start time
      end-time: Select event end time
    venue:
      name: Provide venue name
      address: Provide venue address
      directions: Provide venue directions (google maps)
    speakers:
    - name: Provide Speaker name
      title: Provide Speaker title
      company: Provide Speaker company
    filter-date:
      is-day-1: Select True if event occurs on day 1
      is-day-2: Select True if event occurs on day 2
      is-day-3: Select True if event occurs on day 3
    filter-time:
      is-morning: Select True if event occurs during the morning
      is-daytime: Select True if event occurs during the day
      is-evening: Select True if event occurs during the evening
    filter-type:
      is-session-keynote: Select True if event matches
      is-session-workshop: Select True if event matches
      is-session-general: Select True if event matches
      is-reception: Select True if event matches
      is-track-cx: Select True if event matches
      is-track-engage: Select True if event matches
    layout: page-agenda-single
divider-1: <----- divider, please ignore ----->
primary-navigation:
- title: Agenda
  url: "/agenda/"
- title: Speakers
  url: "/speakers/"
- title: Venue
  url: "/venue/"
- title: Networking
  url: "/networking/"
- title: CX Awards
  url: "/cx-awards/"
- title: FAQs
  url: "/faqs/"
- title: Contact Us
  url: "/contact/"
divider-2: <----- divider, please ignore ----->
registration-url: http://66.media.tumblr.com/a27d0b35ba7fc47ae3fd5021de718d4d/tumblr_mlcpj44xUi1snc7wxo3_250.gif
divider-3: <----- divider, please ignore ----->
justify-trip-url: https://c3.clarabridge.com/wp-content/uploads/2019/06/clarabridge_conference-C3E2019_justify-trip-1.docx
divider-4: <----- divider, please ignore ----->
hero-background-image: "/uploads/c3-test-header.jpg"
hero-logo: "/uploads/c3-logo.png"
hero-logo-alt: logo alt text
hero-header: May 5-8, 2019
hero-date: San Diego, CA
divider-5: <----- divider, please ignore ----->
2020-keynote-speakers-header: 2020 Keynote Speakers
2020-keynote-speakers:
- image: https://picsum.photos/800
  image-alt: provide description of the image
  name: Keynote Speaker Name
  title: Keynote Speaker Title
  company: Keynote Speaker Company
- image: https://picsum.photos/800
  image-alt: provide description of the image
  name: Keynote Speaker Name
  title: Keynote Speaker Title That Is Long
  company: Keynote Speaker Company
- image: https://picsum.photos/800
  image-alt: provide description of the image
  name: Keynote Speaker Name
  title: Keynote Speaker Title That Is Super Super Loooooooooong
  company: Keynote Speaker Company
- image: https://picsum.photos/800
  image-alt: provide description of the image
  name: Keynote Speaker Name
  title: Keynote Speaker Title That Is Super Super Super Super Looooooooooooooong
  company: Keynote Speaker Company
divider-6: <----- divider, please ignore ----->
2020-general-speakers-header: 2020 General Speakers
2020-general-speakers:
- image: https://picsum.photos/800
  image-alt: provide description of the image
  name: General Speaker Name
  title: General Speaker Title
  company: General Speaker Company
- image: https://picsum.photos/800
  image-alt: provide description of the image
  name: General Speaker Name
  title: General Speaker Title
  company: General Speaker Company
- image: https://picsum.photos/800
  image-alt: provide description of the image
  name: General Speaker Name
  title: General Speaker Title
  company: General Speaker Company
- image: https://picsum.photos/800
  image-alt: provide description of the image
  name: General Speaker Name
  title: General Speaker Title
  company: General Speaker Company
divider-7: <----- divider, please ignore ----->
2019-past-speakers-header: 2019 Past Speakers
2019-past-speakers:
- image: https://picsum.photos/800
  image-alt: provide description of the image
- image: https://picsum.photos/800
  image-alt: provide description of the image
- image: https://picsum.photos/800
  image-alt: provide description of the image
- image: https://picsum.photos/800
  image-alt: provide description of the image
- image: https://picsum.photos/800
  image-alt: provide description of the image
- image: https://picsum.photos/800
  image-alt: provide description of the image
- image: https://picsum.photos/800
  image-alt: provide description of the image
- image: https://picsum.photos/800
  image-alt: provide description of the image
divider-8: <----- divider, please ignore ----->
agenda-filter-time-of-day:
- filter: ".morning"
  class: morning
  text-1: Morning
- filter: ".daytime"
  class: daytime
  text-1: Daytime
- filter: ".evening"
  class: evening
  text-1: Evening
agenda-filter-date:
- filter: ".day-1"
  class: day-1
  text-1: Tuesday, May 6th
- filter: ".day-2"
  class: day-2
  text-1: Wednesday, May 7th
- filter: ".day-3"
  class: day-3
  text-1: Thursday, May 8th
agenda-filter-type:
- filter: ".session-keynote"
  class: session-keynote
  text-1: Keynote
- filter: ".session-workshop"
  class: session-workshop
  text-1: Workshop
- filter: ".session-general"
  class: session-general
  text-1: General Session
- filter: ".reception"
  class: reception
  text-1: Reception
- filter: ".track-cx"
  class: track-track
  text-1: CX Track
- filter: ".track-engage"
  class: track-engage
  text-1: Engage Track
divider-9: <----- divider, please ignore ----->
networking-receptions-header: Networking Receptions
networking-receptions:
- image: https://picsum.photos/800
  image-alt: provide description of the image
  title: Title
  location: Location
  location-url: https://www.google.com/maps/dir//San+Diego,+CA/@32.8248175,-117.389171,10z/data=!4m8!4m7!1m0!1m5!1m1!1s0x80d9530fad921e4b:0xd3a21fdfd15df79!2m2!1d-117.1610838!2d32.715738
  date: Date
  time: Time
  body: Description
- image: https://picsum.photos/800
  image-alt: provide description of the image
  title: Title
  location: Location
  location-url: https://www.google.com/maps/dir//San+Diego,+CA/@32.8248175,-117.389171,10z/data=!4m8!4m7!1m0!1m5!1m1!1s0x80d9530fad921e4b:0xd3a21fdfd15df79!2m2!1d-117.1610838!2d32.715738
  date: Date
  time: Time
  body: Description
divider-10: <----- divider, please ignore ----->
contact-background-color: bg-white
contact-header: Contact Us
contact-button-label: Get in Touch
contact-button-url: mailto:events@clarabridge.com?subject=Thanks for reaching out,
  how can we help?
contact-button-style: primary
contact-employees:
- name: Keri Cook
  title: VP, Demand Gen
  email: mailto:keri.cook@clarabridge.com
- name: Kendall Sampson
  title: Manager, Demand Gen
  email: mailto:kendall.sampson@clarabridge.com
- name: Kaitlin Beazell
  title: Marketing Coordinator
  email: mailto:kaitlin.beazell@clarabridge.com
divider-11: <----- divider, please ignore ----->
exclude:
- package.json
- package-lock.json
- Gemfile
- Gemfile.lock
- node_modules
- netlify.toml
- README.md
- vendor
- ".bundle"
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
author: Marcus Relacion
lang: en_US
logo: ''
social:
  name: 
  links: 
twitter:
  username: 
  card: summary
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  typographic_symbols:
    hellip: "..."
permalink: pretty
encoding: utf-8
description: 
url: ''
baseurl: ''
domain: 
repo: https://github.com/marcusrelacion/c3-marketing-site
sass:
  sass_dir: "/assets/styles/"
  style: compressed
