# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - node_modules
  - netlify.toml
  - README.md
  - vendor
  - .bundle

# 2. Installed Gems
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# 3. Gem settings
# Jekyll SEO Tag
title: 2019 C3 Miami
email:
author: Marcus Relacion
lang: en_US
logo: ""
social:
  name:
  links:
twitter:
  username:
  card: summary
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  typographic_symbols: {hellip: ...}

# 4. Jekyll settings
permalink: pretty
timezone: America/New_York

# 5. Collections
collections:
  agenda:
    title: Agenda
    output: true
  posts:
    title: Posts
    output: true
  speakers:
    title: Speakers
    output: false
  sponsors:
    title: Sponsors
    output: false
  uploads:
    title: Uploads
    output: false

defaults:
- scope:
    path: ''
  values:
    has-introduction: true
    introduction-background-color: bg-white
    introduction-header: Introduction
    introduction-body: |-
        Just my luck, no ice. You really think you can fly that thing? Just my luck, no ice. Jaguar shark! So tell me - does it really exist? This thing comes fully loaded. AM/FM radio, reclining bucket seats, and... power windows. Is this my espresso machine? Wh-what is-h-how did you get my espresso machine?

        Did he just throw my cat out of the window?
    introduction-has-button: true
    introduction-button-label: Button
    introduction-button-url: "#"
    introduction-button-style: primary

# 6. Jekyll collections settings

# 7. Site settings
encoding: utf-8
title: 2019 C3 Miami
description: 
email:
author: Marcus Relacion
lang: en_US
logo: ""
url: ""
baseurl: ""
domain: 
repo: "https://github.com/marcusrelacion/c3-marketing-site"
sass:
  sass_dir: "/assets/styles/"
  style: compressed

hero-background-image: /uploads/c3-test-header.jpg
hero-logo: /uploads/c3-logo.png
hero-logo-alt: logo alt text
hero-header: May 5-8, 2019 
hero-date: San Diego, CA

speakers-keynote:
    - image: https://picsum.photos/300
      image-alt:
      name: Keynote Speaker Name
      title: Keynote Speaker Title
      company: Keynote Speaker Company
    - image: https://picsum.photos/300
      image-alt:
      name: Keynote Speaker Name
      title: Keynote Speaker Title That Is Long
      company: Keynote Speaker Company
    - image: https://picsum.photos/300
      image-alt:
      name: Keynote Speaker Name
      title: Keynote Speaker Title That Is Super Super Loooooooooong
      company: Keynote Speaker Company
    - image: https://picsum.photos/300
      image-alt:
      name: Keynote Speaker Name
      title: Keynote Speaker Title That Is Super Super Super Super Looooooooooooooong
      company: Keynote Speaker Company

speakers-general:
    - image: https://picsum.photos/300
      image-alt:
      name: General Speaker Name
      title: General Speaker Title
      company: General Speaker Company
    - image: https://picsum.photos/300
      image-alt:
      name: General Speaker Name
      title: General Speaker Title
      company: General Speaker Company
    - image: https://picsum.photos/300
      image-alt:
      name: General Speaker Name
      title: General Speaker Title
      company: General Speaker Company
    - image: https://picsum.photos/300
      image-alt:
      name: General Speaker Name
      title: General Speaker Title
      company: General Speaker Company
