---
title: 2020 C3 San Diego
timezone: America/New_York
collections:
  agenda:
    title: Agenda
    output: true
    permalink: "/agenda/:title/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
  values:
    has-introduction: true
    introduction-background-color: bg-white
    introduction-header: Introduction
    introduction-body: 
    introduction-has-button: true
    introduction-button-label: Optional Button
    introduction-button-url: "#"
    introduction-button-style: primary
- scope:
    path: ''
    type: agenda
  values:
    description: Provide description of event
    event:
      date: Select event date
      start-time: Select event start time
      end-time: Select event end time
    venue:
      name: Provide venue name
      address: Provide venue address
      directions: Provide venue directions (google maps)
    speakers:
    - name: Provide Speaker name
      title: Provide Speaker title
      company: Provide Speaker company
    filter-date:
      is-day-1: Select True if event occurs on day 1
      is-day-2: Select True if event occurs on day 2
      is-day-3: Select True if event occurs on day 3
    filter-time:
      is-morning: Select True if event occurs during the morning
      is-daytime: Select True if event occurs during the day
      is-evening: Select True if event occurs during the evening
    filter-type:
      is-session-keynote: Select True if event matches
      is-session-workshop: Select True if event matches
      is-session-general: Select True if event matches
      is-reception: Select True if event matches
      is-track-cx: Select True if event matches
      is-track-engage: Select True if event matches
    layout: page-agenda-single
divider-1: "<----- divider, please ignore ----->"
primary-navigation:
- title: Agenda
  url: "/agenda/"
- title: Venue
  url: "/venue/"
- title: Networking
  url: "/networking/"
- title: Sponsors
  url: "/sponsors/"
- title: CX Awards
  url: "/cx-awards/"
- title: FAQs
  url: "/faqs/"
- title: Contact Us
  url: "/contact/"
divider-2: "<----- divider, please ignore ----->"
registration-url: http://66.media.tumblr.com/a27d0b35ba7fc47ae3fd5021de718d4d/tumblr_mlcpj44xUi1snc7wxo3_250.gif
divider-3: "<----- divider, please ignore ----->"
justify-trip-url: https://c3.clarabridge.com/wp-content/uploads/2019/06/clarabridge_conference-C3E2019_justify-trip-1.docx
divider-4: "<----- divider, please ignore ----->"
hero-background-image: "/uploads/c3-san-diego-header.jpg"
hero-logo: "/uploads/c3-logo.png"
hero-logo-alt: logo alt text
hero-header: Clarabridge Customer Connections
hero-date: April 20-22, 2020
hero-location: Hard Rock Hotel San Diego
divider-5: "<----- divider, please ignore ----->"
show-2020-keynote-speakers: false
2020-keynote-speakers-header: Keynote Speakers
2020-keynote-speakers:
- image: https://picsum.photos/800
  image-alt: provide description of the image
  name: Keynote Speaker Name
  title: Keynote Speaker Title
  company: Keynote Speaker Company
- image: https://picsum.photos/800
  image-alt: provide description of the image
  name: Keynote Speaker Name
  title: Keynote Speaker Title That Is Long
  company: Keynote Speaker Company
- image: https://picsum.photos/800
  image-alt: provide description of the image
  name: Keynote Speaker Name
  title: Keynote Speaker Title That Is Super Super Loooooooooong
  company: Keynote Speaker Company
- image: https://picsum.photos/800
  image-alt: provide description of the image
  name: Keynote Speaker Name
  title: Keynote Speaker Title That Is Super Super Super Super Looooooooooooooong
  company: Keynote Speaker Company
divider-6: "<----- divider, please ignore ----->"
show-2020-general-speakers: false
2020-general-speakers-header: General Speakers
2020-general-speakers:
- image: https://picsum.photos/800
  image-alt: provide description of the image
  name: General Speaker Name
  title: General Speaker Title
  company: General Speaker Company
- image: https://picsum.photos/800
  image-alt: provide description of the image
  name: General Speaker Name
  title: General Speaker Title
  company: General Speaker Company
- image: https://picsum.photos/800
  image-alt: provide description of the image
  name: General Speaker Name
  title: General Speaker Title
  company: General Speaker Company
- image: https://picsum.photos/800
  image-alt: provide description of the image
  name: General Speaker Name
  title: General Speaker Title
  company: General Speaker Company
divider-7: "<----- divider, please ignore ----->"
show-2019-past-speakers: true
2019-past-speakers-header: Past Speakers
2019-past-speakers:
- image: "/uploads/speaker-adobe.png"
  image-alt: logo for adobe
- image: "/uploads/speaker-fidelity.png"
  image-alt: logo for fidelity
- image: "/uploads/speaker-sams-club.png"
  image-alt: logo for sams club
- image: "/uploads/speaker-shark-ninja.png"
  image-alt: logo for shark ninja
- image: "/uploads/speaker-united.png"
  image-alt: logo for united
- image: "/uploads/speaker-usa-today.png"
  image-alt: logo for usa today
- image: "/uploads/speaker-usbank.png"
  image-alt: logo for usbank
- image: "/uploads/speaker-vera-bradley.png"
  image-alt: logo for vera bradley
- image: "/uploads/speaker-vmware.png"
  image-alt: logo for vmware
- image: "/uploads/speaker-whirlpool.png"
  image-alt: logo for whirlpool
divider-8: "<----- divider, please ignore ----->"
agenda-filter-time-of-day:
- filter: ".morning"
  class: morning
  text-1: Morning
- filter: ".daytime"
  class: daytime
  text-1: Daytime
- filter: ".evening"
  class: evening
  text-1: Evening
agenda-filter-date:
- filter: ".day-1"
  class: day-1
  text-1: Monday, April 20th
- filter: ".day-2"
  class: day-2
  text-1: Tuesday, April 21st
- filter: ".day-3"
  class: day-3
  text-1: Wednesday, April 22nd
agenda-filter-type:
- filter: ".session-keynote"
  class: session-keynote
  text-1: Keynote
- filter: ".session-workshop"
  class: session-workshop
  text-1: Workshop
- filter: ".session-general"
  class: session-general
  text-1: General Session
- filter: ".reception"
  class: reception
  text-1: Reception
- filter: ".track-customer"
  class: track-customer
  text-1: Customer Track
- filter: ".track-product"
  class: track-product
  text-1: Product Track
divider-9: "<----- divider, please ignore ----->"
networking-receptions-header: Networking Receptions
networking-receptions:
- image: https://picsum.photos/800
  image-alt: provide description of the image
  title: Welcome Reception
  location: TBA
  location-url: 
  date: Monday, April 20th
  time: 6:00 - 9:00 PM
  body: What better way to kick off C3 2020 than by enjoying cocktails and dinner,
    all while networking with your peers! Chat with Clarabridge experts and partners,
    exchange ideas, and make lasting connections.
- image: https://picsum.photos/800
  image-alt: provide description of the image
  title: Welcome Reception
  location: TBA
  location-url: 
  date: Monday, April 20th
  time: 6:00 - 9:00 PM
  body: What better way to kick off C3 2020 than by enjoying cocktails and dinner,
    all while networking with your peers! Chat with Clarabridge experts and partners,
    exchange ideas, and make lasting connections.
venue-header: Venue & Lodging
venue-lodging:
- image: https://picsum.photos/800
  image-alt: provide description of the image
  name: Hard Rock Hotel San Diego
  body: "### Venue\n\nC3 2020 will be hosted at The Hard Rock Hotel San Diego \n\n###
    Lodging\n\nThe Hard Rock Hotel San Diego is located in the heart of downtown in
    the famed Gaslamp Quarter. With a contemporary and chic design, and tons of unique
    features, you’re not just treated like a guest, you’re treated like a rock star."
  has-button: true
  button-url: "/venue/"
  button-label: Find Out More
venue-hotel:
- image: https://picsum.photos/800
  image-alt: provide description of the image
  name: Room Block
  body: |-
    A special room rate of $249 per night has been secured exclusively for C3 attendees. Please note there are a limited number of rooms available, so be sure to book your reservation as soon as possible.

    **Discounted Rate Expires March 27th, 2020**
  has-button: true
  button-url: https://book.passkey.com/go/CLAR0419
  button-label: Book Your Room
contact-background-color: bg-white
contact-header: Contact Us
contact-button-label: Get in Touch
contact-button-url: mailto:events@clarabridge.com?subject=Thanks for reaching out,
  how can we help?
contact-button-style: primary
contact-employees:
- name: Keri Cook
  title: VP, Demand Gen
  email-url: mailto:keri.cook@clarabridge.com
  email-label: keri.cook@clarabridge.com
- name: Kendall Sampson
  title: Manager, Demand Gen
  email-url: mailto:kendall.sampson@clarabridge.com
  email-label: kendall.sampson@clarabridge.com
- name: Kaitlin Beazell
  title: Senior Marketing Coordinator
  email-url: mailto:kaitlin.beazell@clarabridge.com
  email-label: kaitlin.beazell@clarabridge.com
divider-11: "<----- divider, please ignore ----->"
exclude:
- package.json
- package-lock.json
- Gemfile
- Gemfile.lock
- node_modules
- netlify.toml
- README.md
- vendor
- ".bundle"
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
author: Marcus Relacion
lang: en_US
logo: ''
social:
  name: 
  links: 
twitter:
  username: 
  card: summary
markdown: kramdown
kramdown:
  smart_quotes: apos,apos,quot,quot
  typographic_symbols:
    hellip: "..."
permalink: pretty
encoding: utf-8
description: 
url: ''
baseurl: ''
domain: 
repo: https://github.com/marcusrelacion/c3-marketing-site
sass:
  sass_dir: "/assets/styles/"
  style: compressed
